# Generated by Django 3.0.7 on 2020-09-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.TextField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default='None', max_length=26),
        ),
    ]
