# Generated by Django 3.0.7 on 2020-09-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20200902_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.TextField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default=False, max_length=26),
        ),
    ]
