# Generated by Django 3.0.7 on 2020-09-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20200902_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default=None, max_length=26),
        ),
    ]
